// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAxCj4JAnMJ5iRJZ4sTn0DcDGw-JY_FrY',
    appId: '1:239830084549:web:225076fdfe22e36aa2f9ac',
    messagingSenderId: '239830084549',
    projectId: 'scotcentral-8b54c',
    authDomain: 'scotcentral-8b54c.firebaseapp.com',
    storageBucket: 'scotcentral-8b54c.appspot.com',
    measurementId: 'G-MXSV3PGR7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0AE3TF0k0I960N164yLQFx2WC7PQRAKo',
    appId: '1:239830084549:android:29172326efb8724fa2f9ac',
    messagingSenderId: '239830084549',
    projectId: 'scotcentral-8b54c',
    storageBucket: 'scotcentral-8b54c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjPkoEMOiGF50dxXyUATD3iog2yqf5oDM',
    appId: '1:239830084549:ios:7ff31b52378bad5aa2f9ac',
    messagingSenderId: '239830084549',
    projectId: 'scotcentral-8b54c',
    storageBucket: 'scotcentral-8b54c.appspot.com',
    iosClientId:
        '239830084549-0g2ip7it7vk6j5cercuprokr30k6dg9i.apps.googleusercontent.com',
    iosBundleId: 'com.example.woosterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjPkoEMOiGF50dxXyUATD3iog2yqf5oDM',
    appId: '1:239830084549:ios:7ff31b52378bad5aa2f9ac',
    messagingSenderId: '239830084549',
    projectId: 'scotcentral-8b54c',
    storageBucket: 'scotcentral-8b54c.appspot.com',
    iosClientId:
        '239830084549-0g2ip7it7vk6j5cercuprokr30k6dg9i.apps.googleusercontent.com',
    iosBundleId: 'com.example.woosterApp',
  );
}
